id = "brook-code-theme"
name = "Brook Code Theme"
version = "1.0.0"
schema_version = 1
authors = ["Nyoman Sunima <https://nyomansunima.one>", "Weecraft <https://weecraft.club>"]
description = "The best clean code editor theme that combine simplicity and clean look"
repository = "https://github.com/brook-code-theme/zed-theme"